### ISSUE TITLE
iteritems() is outdated for python3, replace with items()

### ISSUE THREAD

**Issue by jhelmich2** [saltstack-formulas/smokeping-formula#3]
While using this formula to deploy smokeping on a server running Debian 10 (Buster) which comes with python3, it couldn't push the Targets, Probes and Alerts due to having iteritems() in them. Replacing it with items() solved this and also proved to be backwards compatible with python2 (tested on Debian 9 (Stretch) machines with pythonversion 2.7.13 and Debian Buster with pythonversion 3.7.3).

**Comment by myii** [comment]
Thanks for reporting this @jhelmich2.  Would you be able to provide a PR for this?

**Comment by jhelmich2** [comment]
I think I created one, if someone could check for it.

**Comment by myii** [comment]
Fixed by #5.
